#!/bin/bash
# A script that uses 'xdg-mime' to fetch the default apps on the system.
# Dependencies: 'xdg-mime', 'xdg-settings'
# Written by simonizor 5/27/2017 - http://www.simonizor.gq/linuxapps

bold=$(tput bold; tput setaf 7)
norm=$(tput sgr0)

programisinstalled () {
    type "$1" >/dev/null 2>&1
}

xdgfetchmain () {
    case $1 in
        -h*|--h*)
            printf "${bold}xdgfetch usage${norm}:\n${bold}xdgfetch${norm}:           Shows current system info, xdg session, default applications, and default directories\n${bold}xdgfetch -h${norm}:        Shows this help output\n${bold}xdgfetch -c${norm}:        Changes the color of bold text.  Works with any valid tput color.\n  Ex: 'xdgfetch -c 1', 'xdgfetch -c 1 -x'\n${bold}xdgfetch -i${norm}:        Shows system info from '/proc/'\n${bold}xdgfetch -s${norm}:        Shows current xdg session info\n${bold}xdgfetch -a${norm}:        Shows default xdg applications\n${bold}xdgfetch -d${norm}:        Shows default xdg directories\n${bold}xdgfetch --verbose${norm}: Shows output in xdg syntax\n"
            ;;
        -c*|--c*)
            case $2 in
                0*|1*|2*|3*|4*|5*|6*|7*|8*|9*)
                    bold=$(tput bold; tput setaf $2)
                    xdgfetchmain "$3"
                    ;;
                *)
                    echo "Invalid color choice."
                    exit 1
                    ;;
            esac
            ;;
        -i*|--i*)
            VERSION_SIGNATURE="${bold}OS Version:    ${norm}$(cat /proc/version_signature)"
            UPTIME="${bold}Uptime:        ${norm}$(cat /proc/uptime)"
            CPU_MODEL_NAME="${bold}CPU:           ${norm}$(cat /proc/cpuinfo | grep 'model name' | head -n 1 | cut -c 14-)"
            CPU_CORES="${bold}CPU Cores:     ${norm}$(cat /proc/cpuinfo | grep 'cpu MHz' | wc -l)"
            CPU_MHZ="${bold}CPU MHz:       ${norm}$(cat /proc/cpuinfo | grep 'cpu MHz' | cut -c 12- | tr '\n' ' ')"
            CPU_CACHE="${bold}CPU Cache:     ${norm}$(cat /proc/cpuinfo | grep 'cache size' | head -n 1 | cut -c 14-)"
            CPU_MODEL="${bold}CPU Model:     ${norm}$(cat /proc/cpuinfo | grep 'model' | head -n 1 | cut -c 10-)"
            CPU_STEPPING="${bold}CPU Stepping:  ${norm}$(cat /proc/cpuinfo | grep 'stepping' | head -n 1 | cut -c 12-)"
            LOADAVG="${bold}Load Average:  ${norm}$(cat /proc/loadavg)"
            SOUND_CARDS="${bold}Sound Card(s):\n${norm}$(cat /proc/asound/cards | cut -c 2-)"
            GPUS="${bold}GPU(s):\n${norm}$(lspci -k | grep -A 3 VGA)"
            RAM_TOTAL="${bold}RAM Total:     ${norm}$(cat /proc/meminfo | grep MemTotal | cut -c 18-)"
            RAM_USED="${bold}RAM Used:      ${norm}$(cat /proc/meminfo | grep Cached | cut -c 18- | head -n 1)"
            RAM_AVAILABLE="${bold}RAM Available: ${norm}$(cat /proc/meminfo | grep MemAvailable | cut -c 18-)"
            SWAP_TOTAL="${bold}Swap Total:    ${norm}$(cat /proc/meminfo | grep SwapTotal | cut -c 18-)"
            SWAP_USED="${bold}Swap Used:     ${norm}$(cat /proc/meminfo | grep SwapCached | cut -c 22-)"
            SWAP_FREE="${bold}Swap Free:     ${norm}$(cat /proc/meminfo | grep SwapFree | cut -c 18-)"
            printf "${bold}System info:${norm}\n$VERSION_SIGNATURE\n$UPTIME\n$CPU_MODEL_NAME\n$CPU_CORES\n$CPU_MHZ\n$CPU_CACHE\n$CPU_MODEL\n$CPU_STEPPING\n$LOADAVG\n$SOUND_CARDS\n$GPUS\n$RAM_TOTAL\n$RAM_USED\n$RAM_AVAILABLE\n$SWAP_TOTAL\n$SWAP_USED\n$SWAP_FREE\n"
            ;;
        -s*|--s*)
            XDG_CURRENT_DESKTOP="${bold}Desktop:       ${norm}$XDG_CURRENT_DESKTOP"
            XDG_SESSION_TYPE="${bold}Type:          ${norm}$XDG_SESSION_TYPE"
            printf "${bold}Current xdg session:${norm}\n$XDG_CURRENT_DESKTOP\n$XDG_SESSION_TYPE\n"
            ;;
        -a*|--a*)
            XDGFILEMANAGER="$(xdg-mime query default inode/directory)" || XDGFILEMANAGER="Not set!        "
            case $XDGFILEMANAGER in
                *dolphin*|*Dolphin*)
                     XDGFILEMANAGER="${bold}File Manager:  ${norm}Dolphin"
                    ;;
                *thunar*|*Thunar*)
                     XDGFILEMANAGER="${bold}File Manager:  ${norm}Thunar"
                    ;;
                *pcmanfm*|*PCManFM*)
                     XDGFILEMANAGER=o "${bold}File Manager:  ${norm}PCManFM"
                    ;;
                *ranger*|*Ranger*)
                     XDGFILEMANAGER= "${bold}File Manager:  ${norm}ranger"
                    ;;
                *)
                     XDGFILEMANAGER= "${bold}File Manager:  ${norm}${XDGFILEMANAGER::-8}"
                    ;;
            esac
            XDGBROWSER="$(xdg-settings get default-web-browser)" || XDGBROWSER="Not set!        "
            case $XDGBROWSER in
                *Pale*|*pale*)
                    XDGBROWSER="${bold}Browser:       ${norm}Pale Moon"
                    ;;
                *firefox*)
                    XDGBROWSER="${bold}Browser:       ${norm}Firefox"
                    ;;
                *google*)
                    XDGBROWSER="${bold}Browser:       ${norm}Google Chrome"
                    ;;
                *chromium*)
                    XDGBROWSER="${bold}Browser:       ${norm}Chromium"
                    ;;
                *)
                    XDGBROWSER="${bold}Browser:       ${norm}${XDGBROWSER::-8}"
                    ;;
            esac
            XDGMAILTO="$(xdg-mime query default x-scheme-handler/mailto)" || XDGMAILTO="Not set!        "
            case $XDGMAILTO in
                *thunderbird*|*Thunderbird*)
                    XDGMAILTO="${bold}Email:         ${norm}Thunderbird"
                    ;;
                *kmail*)
                    XDGMAILTO="${bold}Email:         ${norm}KMail"
                    ;;
                *)
                    XDGMAILTO="${bold}Email:         ${norm}${XDGMAILTO::-8}"
                    ;;
            esac
            XDGAUDIO="$(xdg-mime query default audio/flac)" || XDGAUDIO="Not set!        "
            case $XDGAUDIO in
                *audacious*|*Audacious*)
                    XDGAUDIO="${bold}Audio:         ${norm}Audacious"
                    ;;
                *mpv*)
                    XDGAUDIO="${bold}Audio:         ${norm}mpv"
                    ;;
                *vlc*|*VLC*)
                    XDGAUDIO="${bold}Audio:         ${norm}VLC"
                    ;;
                *amarok*|*Amarok*)
                    XDGAUDIO="${bold}Audio:         ${norm}Amarok"
                    ;;
                *deadbeef*)
                    XDGAUDIO="${bold}Audio:         ${norm}DeaDBeeF"
                    ;;
                *)
                    XDGAUDIO="${bold}Audio:         ${norm}${XDGAUDIO::-8}"
                    ;;
            esac
            XDGVIDEO="$(xdg-mime query default video/mp4)" || XDGVIDEO="Not set!        "
            case $XDGVIDEO in
                *mpv*)
                    XDGVIDEO="${bold}Video:         ${norm}mpv"
                    ;;
                *vlc*|*VLC*)
                    XDGVIDEO="${bold}Video:         ${norm}VLC"
                    ;;
                *mplayer*)
                    XDGVIDEO="${bold}Video:         ${norm}Mplayer"
                    ;;
                *)
                    XDGVIDEO="${bold}Video:         ${norm}${XDGVIDEO::-8}"
                    ;;
            esac
            XDGIMAGE="$(xdg-mime query default image/png)" || XDGIMAGE="Not set!        "
            case $XDGIMAGE in
                *gwenview*|*Gwenview*)
                    XDGIMAGE="${bold}Image:         ${norm}Gwenview"
                    ;;
                *gimp*|*Gimp*|*GIMP*)
                    XDGIMAGE="${bold}Image:         ${norm}GIMP"
                    ;;
                *krita*|*Krita*)
                    XDGIMAGE="${bold}Image:         ${norm}Krita"
                    ;;
                *mtpaint*)
                    XDGIMAGE="${bold}Image:         ${norm}mtpaint"
                    ;;
                *)
                    XDGIMAGE="${bold}Image:         ${norm}${XDGIMAGE::-8}"
                    ;;
            esac
            XDGTEXT="$(xdg-mime query default text/plain)" || XDGTEXT="Not set!        "
            case $XDGTEXT in
                *code*)
                    XDGTEXT="${bold}Text:          ${norm}VSCode"
                    ;;
                *atom*|*Atom*)
                    XDGTEXT="${bold}Text:          ${norm}Atom"
                    ;;
                *gedit*|*Gedit*)
                    XDGTEXT="${bold}Text:          ${norm}gedit"
                    ;;
                *mousepad*|*Mousepad*)
                    XDGTEXT="${bold}Text:          ${norm}Mousepad"
                    ;;
                *notepadqq*|*Notepadqq*)
                    XDGTEXT="${bold}Text:          ${norm}notepadqq"
                    ;;
                *geany*|*Geany*)
                    XDGTEXT="${bold}Text:          ${norm}Geany"
                    ;;
                *kwrite*|*KWrite*)
                    XDGTEXT="${bold}Text:          ${norm}KWrite"
                    ;;
                *)
                    XDGTEXT="${bold}Text:          ${norm}${XDGTEXT::-8}"
                    ;;
            esac
            XDGOFFICE="$(xdg-mime query default application/vnd.ms-word)" || XDGOFFICE="Not set!        "
            case $XDGOFFICE in
                *libreoffice*|*LibreOffice*)
                    XDGOFFICE="${bold}Office:        ${norm}LibreOffice"
                    ;;
                *)
                    XDGOFFICE="${bold}Office:        ${norm}${XDGOFFICE::-8}"
                    ;;
            esac
            XDGARCHIVE="$(xdg-mime query default application/x-tar)" || XDGARCHIVE="Not set!        "
            case $XDGARCHIVE in
                *Ark*|*ark*)
                    XDGARCHIVE="${bold}Archive:       ${norm}Ark"
                    ;;
                *)
                    XDGARCHIVE="${bold}Archive:       ${norm}${XDGARCHIVE::-8}"
                    ;;
            esac
            XDGPGP="$(xdg-mime query default application/pgp-keys)" || XDGPGP="Not set!        "
            case $XDGPGP in
                *kgpg*|*KGpg*)
                    XDGPGP="${bold}PGP:           ${norm}KGpg"
                    ;;
                *)
                    XDGPGP="${bold}PGP:           ${norm}${XDGPGP::-8}"
                    ;;
            esac
            printf "${bold}Default xdg applications:${norm}\n$XDGFILEMANAGER\n$XDGMAILTO\n$XDGAUDIO\n$XDGVIDEO\n$XDGIMAGE\n$XDGTEXT\n$XDGOFFICE\n$XDGARCHIVE\n$XDGPGP\n"
            ;;
        -d*|--d*)
            if [ -f ~/.config/user-dirs.dirs ]; then
                . ~/.config/user-dirs.dirs
                XDG_DESKTOP_DIR="${bold}Desktop:       ${norm}$XDG_DESKTOP_DIR"
                XDG_DOCUMENTS_DIR="${bold}Documents:     ${norm}$XDG_DOCUMENTS_DIR"
                XDG_DOWNLOAD_DIR="${bold}Downloads:     ${norm}$XDG_DOWNLOAD_DIR"
                XDG_MUSIC_DIR="${bold}Music:         ${norm}$XDG_MUSIC_DIR"
                XDG_PICTURES_DIR="${bold}Pictures:      ${norm}$XDG_PICTURES_DIR"
                XDG_PUBLICSHARE_DIR="${bold}Public:        ${norm}$XDG_PUBLICSHARE_DIR"
                XDG_TEMPLATES_DIR="${bold}Templates:     ${norm}$XDG_TEMPLATES_DIR"
                XDG_VIDEOS_DIR="${bold}Videos:        ${norm}$XDG_VIDEOS_DIR"
            fi
            printf "${bold}Default xdg directories:${norm}\n$XDG_DESKTOP_DIR\n$XDG_DOCUMENTS_DIR\n$XDG_DOWNLOAD_DIR\n$XDG_MUSIC_DIR\n$XDG_PICTURES_DIR\n$XDG_PUBLICSHARE_DIR\n$XDG_TEMPLATES_DIR\n$XDG_VIDEOS_DIR\n"
            ;;
        -verbose|--verbose)
            VERSION_SIGNATURE="${bold}OS Version:               ${norm}$(cat /proc/version_signature)"
            UPTIME="${bold}Uptime:                   ${norm}$(cat /proc/uptime)"
            CPU_MODEL_NAME="${bold}CPU:                      ${norm}$(cat /proc/cpuinfo | grep 'model name' | head -n 1 | cut -c 14-)"
            CPU_CORES="${bold}CPU Cores:                ${norm}$(cat /proc/cpuinfo | grep 'cpu MHz' | wc -l)"
            CPU_MHZ="${bold}CPU MHz:                  ${norm}$(cat /proc/cpuinfo | grep 'cpu MHz' | cut -c 12- | tr '\n' ' ')"
            CPU_CACHE="${bold}CPU Cache:                ${norm}$(cat /proc/cpuinfo | grep 'cache size' | head -n 1 | cut -c 14-)"
            CPU_MODEL="${bold}CPU Model:                ${norm}$(cat /proc/cpuinfo | grep 'model' | head -n 1 | cut -c 10-)"
            CPU_STEPPING="${bold}CPU Stepping:             ${norm}$(cat /proc/cpuinfo | grep 'stepping' | head -n 1 | cut -c 12-)"
            LOADAVG="${bold}Load Average:             ${norm}$(cat /proc/loadavg)"
            SOUND_CARDS="${bold}Sound Card(s):\n${norm}$(cat /proc/asound/cards | cut -c 2-)"
            GPUS="${bold}GPU(s):\n${norm}$(lspci -k | grep -A 3 VGA)"
            RAM_TOTAL="${bold}RAM Total:                ${norm}$(cat /proc/meminfo | grep MemTotal | cut -c 18-)"
            RAM_USED="${bold}RAM Used:                 ${norm}$(cat /proc/meminfo | grep Cached | cut -c 18- | head -n 1)"
            RAM_AVAILABLE="${bold}RAM Available:            ${norm}$(cat /proc/meminfo | grep MemAvailable | cut -c 18-)"
            SWAP_TOTAL="${bold}Swap Total:               ${norm}$(cat /proc/meminfo | grep SwapTotal | cut -c 18-)"
            SWAP_USED="${bold}Swap Used:                ${norm}$(cat /proc/meminfo | grep SwapCached | cut -c 22-)"
            SWAP_FREE="${bold}Swap Free:                ${norm}$(cat /proc/meminfo | grep SwapFree | cut -c 18-)"
            XDG_CURRENT_DESKTOP="${bold}XDG_CURRENT_DESKTOP:      ${norm}$XDG_CURRENT_DESKTOP"
            XDG_SESSION_TYPE="${bold}XDG_SESSION_TYPE:         ${norm}$XDG_SESSION_TYPE"
            XDGFILEMANAGER="$(xdg-mime query default inode/directory)" || XDGFILEMANAGER="Not set!        "
            XDGFILEMANAGER="${bold}inode/directory:          ${norm}$XDGFILEMANAGER"
            XDGBROWSER="$(xdg-settings get default-web-browser)" || XDGBROWSER="Not set!        "
            XDGBROWSER="${bold}default-web-browser:      ${norm}$XDGBROWSER"
            XDGMAILTO="$(xdg-mime query default x-scheme-handler/mailto)" || XDGMAILTO="Not set!        "
            XDGMAILTO="${bold}x-scheme-handler/mailto:  ${norm}$XDGMAILTO"
            XDGAUDIO="$(xdg-mime query default audio/flac)" || XDGAUDIO="Not set!        "
            XDGAUDIO="${bold}audio/flac:               ${norm}$XDGAUDIO"
            XDGVIDEO="$(xdg-mime query default video/mp4)" || XDGVIDEO="Not set!        "
            XDGVIDEO="${bold}video/mp4:                ${norm}$XDGVIDEO"
            XDGIMAGE="$(xdg-mime query default image/png)" || XDGIMAGE="Not set!        "
            XDGIMAGE="${bold}image/png:                ${norm}$XDGIMAGE"
            XDGTEXT="$(xdg-mime query default text/plain)" || XDGTEXT="Not set!        "
            XDGTEXT="${bold}text/plain:               ${norm}$XDGTEXT"
            XDGOFFICE="$(xdg-mime query default application/vnd.ms-word)" || XDGOFFICE="Not set!        "
            XDGOFFICE="${bold}application/vnd.ms-word:  ${norm}$XDGOFFICE"
            XDGARCHIVE="$(xdg-mime query default application/x-tar)" || XDGARCHIVE="Not set!        "
            XDGARCHIVE="${bold}application/x-tar:        ${norm}$XDGARCHIVE"
            XDGPGP="$(xdg-mime query default application/pgp-keys)" || XDGPGP="Not set!        "
            XDGPGP="${bold}application/pgp-keys:     ${norm}$XDGPGP"
            if [ -f ~/.config/user-dirs.dirs ]; then
                . ~/.config/user-dirs.dirs
                XDG_DESKTOP_DIR="${bold}XDG_DESKTOP_DIR:         ${norm}$XDG_DESKTOP_DIR"
                XDG_DOCUMENTS_DIR="${bold}XDG_DOCUMENTS_DIR:       ${norm}$XDG_DOCUMENTS_DIR"
                XDG_DOWNLOAD_DIR="${bold}XDG_DOWNLOAD_DIR:        ${norm}$XDG_DOWNLOAD_DIR"
                XDG_MUSIC_DIR="${bold}XDG_MUSIC_DIR:           ${norm}$XDG_MUSIC_DIR"
                XDG_PICTURES_DIR="${bold}XDG_PICTURES_DIR:        ${norm}$XDG_PICTURES_DIR"
                XDG_PUBLICSHARE_DIR="${bold}XDG_PUBLICSHARE_DIR:     ${norm}$XDG_PUBLICSHARE_DIR"
                XDG_TEMPLATES_DIR="${bold}XDG_TEMPLATES_DIR:       ${norm}$XDG_TEMPLATES_DIR"
                XDG_VIDEOS_DIR="${bold}XDG_VIDEOS_DIR:          ${norm}$XDG_VIDEOS_DIR"
            fi
            printf "${bold}System info:${norm}\n$VERSION_SIGNATURE\n$UPTIME\n$CPU_MODEL_NAME\n$CPU_CORES\n$CPU_MHZ\n$CPU_CACHE\n$CPU_MODEL\n$CPU_STEPPING\n$LOADAVG\n$SOUND_CARDS\n$GPUS\n$RAM_TOTAL\n$RAM_USED\n$RAM_AVAILABLE\n$SWAP_TOTAL\n$SWAP_USED\n$SWAP_FREE\n\n${bold}Current xdg session:${norm}\n$XDG_CURRENT_DESKTOP\n$XDG_SESSION_TYPE\n\n${bold}Default xdg applications:${norm}\n$XDGFILEMANAGER\n$XDGMAILTO\n$XDGAUDIO\n$XDGVIDEO\n$XDGIMAGE\n$XDGTEXT\n$XDGOFFICE\n$XDGARCHIVE\n$XDGPGP\n\n${bold}Default xdg directories:${norm}\n$XDG_DESKTOP_DIR\n$XDG_DOCUMENTS_DIR\n$XDG_DOWNLOAD_DIR\n$XDG_MUSIC_DIR\n$XDG_PICTURES_DIR\n$XDG_PUBLICSHARE_DIR\n$XDG_TEMPLATES_DIR\n$XDG_VIDEOS_DIR\n"
            ;;
        *)
            VERSION_SIGNATURE="${bold}OS Version:    ${norm}$(cat /proc/version_signature)"
            UPTIME="${bold}Uptime:        ${norm}$(cat /proc/uptime)"
            CPU_MODEL_NAME="${bold}CPU:           ${norm}$(cat /proc/cpuinfo | grep 'model name' | head -n 1 | cut -c 14-)"
            CPU_CORES="${bold}CPU Cores:     ${norm}$(cat /proc/cpuinfo | grep 'cpu MHz' | wc -l)"
            CPU_MHZ="${bold}CPU MHz:       ${norm}$(cat /proc/cpuinfo | grep 'cpu MHz' | cut -c 12- | tr '\n' ' ')"
            CPU_CACHE="${bold}CPU Cache:     ${norm}$(cat /proc/cpuinfo | grep 'cache size' | head -n 1 | cut -c 14-)"
            CPU_MODEL="${bold}CPU Model:     ${norm}$(cat /proc/cpuinfo | grep 'model' | head -n 1 | cut -c 10-)"
            CPU_STEPPING="${bold}CPU Stepping:  ${norm}$(cat /proc/cpuinfo | grep 'stepping' | head -n 1 | cut -c 12-)"
            LOADAVG="${bold}Load Average:  ${norm}$(cat /proc/loadavg)"
            SOUND_CARDS="${bold}Sound Card(s):\n${norm}$(cat /proc/asound/cards | cut -c 2-)"
            GPUS="${bold}GPU(s):\n${norm}$(lspci -k | grep -A 3 VGA)"
            RAM_TOTAL="$(cat /proc/meminfo | grep MemTotal | cut -c 18- | tr -d 'kB')"
            RAM_TOTAL="${bold}RAM Total:     ${norm}$(expr $RAM_TOTAL / 1000) mB"
            RAM_USED="$(cat /proc/meminfo | grep Cached | cut -c 18- | head -n 1 | tr -d 'kB')"
            if [[ "$RAM_USED" > "1000" ]]; then
                RAM_USED="${bold}RAM Used:      ${norm}$(expr $RAM_USED / 1000) mB"
            else
                RAM_USED="${bold}RAM Used:  ${norm}${RAM_USED}kB"
            fi
            RAM_AVAILABLE="$(cat /proc/meminfo | grep MemAvailable | cut -c 18- | tr -d 'kB')"
            if [[ "$RAM_AVAILABLE" > "1000" ]]; then
                RAM_AVAILABLE="${bold}RAM Free:      ${norm}$(expr $RAM_AVAILABLE / 1000) mB"
            else
                RAM_AVAILABLE="${bold}RAM Free:  ${norm}${RAM_AVAILABLE}kB"
            fi
            SWAP_TOTAL="$(cat /proc/meminfo | grep SwapTotal | cut -c 18- | tr -d 'kB')"
            SWAP_TOTAL="${bold}Swap Total:    ${norm}$(expr $SWAP_TOTAL / 1000) mB"
            SWAP_USED="$(cat /proc/meminfo | grep SwapCached | cut -c 18- | tr -d 'kB')"
            if [[ "$SWAP_USED" > "1000" ]]; then
                SWAP_USED="${bold}Swap Used:        ${norm}$(expr $SWAP_USED / 1000) mB"
            else
                SWAP_USED="${bold}Swap Used:  ${norm}${SWAP_USED}kB"
            fi
            SWAP_FREE="$(cat /proc/meminfo | grep SwapFree | cut -c 18- | tr -d 'kB')"
            if [[ "$SWAP_FREE" > "1000" ]]; then
                SWAP_FREE="${bold}Swap Free:     ${norm}$(expr $SWAP_FREE / 1000) mB"
            else
                SWAP_FREE="${bold}Swap Free:  ${norm}${SWAP_FREE}kB"
            fi
            
            XDG_CURRENT_DESKTOP="${bold}Desktop:       ${norm}$XDG_CURRENT_DESKTOP"
            XDG_SESSION_TYPE="${bold}Type:          ${norm}$XDG_SESSION_TYPE"
            XDGFILEMANAGER="$(xdg-mime query default inode/directory)" || XDGFILEMANAGER="Not set!        "
            case $XDGFILEMANAGER in
                *dolphin*|*Dolphin*)
                     XDGFILEMANAGER="${bold}File Manager:  ${norm}Dolphin"
                    ;;
                *thunar*|*Thunar*)
                     XDGFILEMANAGER="${bold}File Manager:  ${norm}Thunar"
                    ;;
                *pcmanfm*|*PCManFM*)
                     XDGFILEMANAGER=o "${bold}File Manager:  ${norm}PCManFM"
                    ;;
                *ranger*|*Ranger*)
                     XDGFILEMANAGER= "${bold}File Manager:  ${norm}ranger"
                    ;;
                *)
                     XDGFILEMANAGER= "${bold}File Manager:  ${norm}${XDGFILEMANAGER::-8}"
                    ;;
            esac
            XDGBROWSER="$(xdg-settings get default-web-browser)" || XDGBROWSER="Not set!        "
            case $XDGBROWSER in
                *Pale*|*pale*)
                    XDGBROWSER="${bold}Browser:       ${norm}Pale Moon"
                    ;;
                *firefox*)
                    XDGBROWSER="${bold}Browser:       ${norm}Firefox"
                    ;;
                *google*)
                    XDGBROWSER="${bold}Browser:       ${norm}Google Chrome"
                    ;;
                *chromium*)
                    XDGBROWSER="${bold}Browser:       ${norm}Chromium"
                    ;;
                *)
                    XDGBROWSER="${bold}Browser:       ${norm}${XDGBROWSER::-8}"
                    ;;
            esac
            XDGMAILTO="$(xdg-mime query default x-scheme-handler/mailto)" || XDGMAILTO="Not set!        "
            case $XDGMAILTO in
                *thunderbird*|*Thunderbird*)
                    XDGMAILTO="${bold}Email:         ${norm}Thunderbird"
                    ;;
                *kmail*)
                    XDGMAILTO="${bold}Email:         ${norm}KMail"
                    ;;
                *)
                    XDGMAILTO="${bold}Email:         ${norm}${XDGMAILTO::-8}"
                    ;;
            esac
            XDGAUDIO="$(xdg-mime query default audio/flac)" || XDGAUDIO="Not set!        "
            case $XDGAUDIO in
                *audacious*|*Audacious*)
                    XDGAUDIO="${bold}Audio:         ${norm}Audacious"
                    ;;
                *mpv*)
                    XDGAUDIO="${bold}Audio:         ${norm}mpv"
                    ;;
                *vlc*|*VLC*)
                    XDGAUDIO="${bold}Audio:         ${norm}VLC"
                    ;;
                *amarok*|*Amarok*)
                    XDGAUDIO="${bold}Audio:         ${norm}Amarok"
                    ;;
                *deadbeef*)
                    XDGAUDIO="${bold}Audio:         ${norm}DeaDBeeF"
                    ;;
                *)
                    XDGAUDIO="${bold}Audio:         ${norm}${XDGAUDIO::-8}"
                    ;;
            esac
            XDGVIDEO="$(xdg-mime query default video/mp4)" || XDGVIDEO="Not set!        "
            case $XDGVIDEO in
                *mpv*)
                    XDGVIDEO="${bold}Video:         ${norm}mpv"
                    ;;
                *vlc*|*VLC*)
                    XDGVIDEO="${bold}Video:         ${norm}VLC"
                    ;;
                *mplayer*)
                    XDGVIDEO="${bold}Video:         ${norm}Mplayer"
                    ;;
                *)
                    XDGVIDEO="${bold}Video:         ${norm}${XDGVIDEO::-8}"
                    ;;
            esac
            XDGIMAGE="$(xdg-mime query default image/png)" || XDGIMAGE="Not set!        "
            case $XDGIMAGE in
                *gwenview*|*Gwenview*)
                    XDGIMAGE="${bold}Image:         ${norm}Gwenview"
                    ;;
                *gimp*|*Gimp*|*GIMP*)
                    XDGIMAGE="${bold}Image:         ${norm}GIMP"
                    ;;
                *krita*|*Krita*)
                    XDGIMAGE="${bold}Image:         ${norm}Krita"
                    ;;
                *mtpaint*)
                    XDGIMAGE="${bold}Image:         ${norm}mtpaint"
                    ;;
                *)
                    XDGIMAGE="${bold}Image:         ${norm}${XDGIMAGE::-8}"
                    ;;
            esac
            XDGTEXT="$(xdg-mime query default text/plain)" || XDGTEXT="Not set!        "
            case $XDGTEXT in
                *code*)
                    XDGTEXT="${bold}Text:          ${norm}VSCode"
                    ;;
                *atom*|*Atom*)
                    XDGTEXT="${bold}Text:          ${norm}Atom"
                    ;;
                *gedit*|*Gedit*)
                    XDGTEXT="${bold}Text:          ${norm}gedit"
                    ;;
                *mousepad*|*Mousepad*)
                    XDGTEXT="${bold}Text:          ${norm}Mousepad"
                    ;;
                *notepadqq*|*Notepadqq*)
                    XDGTEXT="${bold}Text:          ${norm}notepadqq"
                    ;;
                *geany*|*Geany*)
                    XDGTEXT="${bold}Text:          ${norm}Geany"
                    ;;
                *kwrite*|*KWrite*)
                    XDGTEXT="${bold}Text:          ${norm}KWrite"
                    ;;
                *)
                    XDGTEXT="${bold}Text:          ${norm}${XDGTEXT::-8}"
                    ;;
            esac
            XDGOFFICE="$(xdg-mime query default application/vnd.ms-word)" || XDGOFFICE="Not set!        "
            case $XDGOFFICE in
                *libreoffice*|*LibreOffice*)
                    XDGOFFICE="${bold}Office:        ${norm}LibreOffice"
                    ;;
                *)
                    XDGOFFICE="${bold}Office:        ${norm}${XDGOFFICE::-8}"
                    ;;
            esac
            XDGARCHIVE="$(xdg-mime query default application/x-tar)" || XDGARCHIVE="Not set!        "
            case $XDGARCHIVE in
                *Ark*|*ark*)
                    XDGARCHIVE="${bold}Archive:       ${norm}Ark"
                    ;;
                *)
                    XDGARCHIVE="${bold}Archive:       ${norm}${XDGARCHIVE::-8}"
                    ;;
            esac
            XDGPGP="$(xdg-mime query default application/pgp-keys)" || XDGPGP="Not set!        "
            case $XDGPGP in
                *kgpg*|*KGpg*)
                    XDGPGP="${bold}PGP:           ${norm}KGpg"
                    ;;
                *)
                    XDGPGP="${bold}PGP:           ${norm}${XDGPGP::-8}"
                    ;;
            esac
            if [ -f ~/.config/user-dirs.dirs ]; then
                . ~/.config/user-dirs.dirs
                XDG_DESKTOP_DIR="${bold}Desktop:       ${norm}$XDG_DESKTOP_DIR"
                XDG_DOCUMENTS_DIR="${bold}Documents:     ${norm}$XDG_DOCUMENTS_DIR"
                XDG_DOWNLOAD_DIR="${bold}Downloads:     ${norm}$XDG_DOWNLOAD_DIR"
                XDG_MUSIC_DIR="${bold}Music:         ${norm}$XDG_MUSIC_DIR"
                XDG_PICTURES_DIR="${bold}Pictures:      ${norm}$XDG_PICTURES_DIR"
                XDG_PUBLICSHARE_DIR="${bold}Public:        ${norm}$XDG_PUBLICSHARE_DIR"
                XDG_TEMPLATES_DIR="${bold}Templates:     ${norm}$XDG_TEMPLATES_DIR"
                XDG_VIDEOS_DIR="${bold}Videos:        ${norm}$XDG_VIDEOS_DIR"
            fi
            printf "${bold}System info:${norm}\n$VERSION_SIGNATURE\n$UPTIME\n$CPU_MODEL_NAME\n$CPU_CORES\n$CPU_MHZ\n$CPU_CACHE\n$CPU_MODEL\n$CPU_STEPPING\n$LOADAVG\n$SOUND_CARDS\n$GPUS\n$RAM_TOTAL\n$RAM_USED\n$RAM_AVAILABLE\n$SWAP_TOTAL\n$SWAP_USED\n$SWAP_FREE\n\n${bold}Current xdg session:${norm}\n$XDG_CURRENT_DESKTOP\n$XDG_SESSION_TYPE\n\n${bold}Default xdg applications:${norm}\n$XDGFILEMANAGER\n$XDGMAILTO\n$XDGAUDIO\n$XDGVIDEO\n$XDGIMAGE\n$XDGTEXT\n$XDGOFFICE\n$XDGARCHIVE\n$XDGPGP\n\n${bold}Default xdg directories:${norm}\n$XDG_DESKTOP_DIR\n$XDG_DOCUMENTS_DIR\n$XDG_DOWNLOAD_DIR\n$XDG_MUSIC_DIR\n$XDG_PICTURES_DIR\n$XDG_PUBLICSHARE_DIR\n$XDG_TEMPLATES_DIR\n$XDG_VIDEOS_DIR\n"
    esac
}

programisinstalled "xdg-mime" || { echo "xdg-mime is not installed!"; exit 1; }
programisinstalled "xdg-settings" || { echo "xdg-settings is not installed!"; exit 1; }
if [ ! -z "$2" ]; then
    case $3 in
        0*|1*|2*|3*|4*|5*|6*|7*|8*|9*)
            bold=$(tput bold; tput setaf $3)
            xdgfetchmain "$@"
            ;;
        *)
            xdgfetchmain "$@"
            ;;
    esac
else
    xdgfetchmain "$@"
fi